// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'option': string;
  'option-active': string;
  'option-icon-active': string;
}
export const cssExports: CssExports;
export default cssExports;
