// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form-row': string;
  'icon-arrow': string;
  'icon-arrow-container': string;
  'result-inner': string;
  'result-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
