// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dark': string;
  'iconContainer': string;
  'popper-content': string;
  'popper-end': string;
  'popper-opened': string;
  'scroll-area': string;
  'select': string;
  'select-active': string;
  'select-placeholder': string;
}
export const cssExports: CssExports;
export default cssExports;
