// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'dark': string;
  'iconContainer': string;
  'selectorLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
