// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'input-container': string;
  'input-icon': string;
  'input-placeholder': string;
}
export const cssExports: CssExports;
export default cssExports;
